return {
      avplay        = require("compact.avplay"),  
      menu          = require("compact.menu"),
      layout        = require("compact.layout"),
      common        = require("compact.common"),

      unitybar      = require("compact.unitybar"),
      tagmenu       = require("compact.tagmenu"),
      titlebar      = require("compact.titlebar"),
      tasklist      = require("compact.tasklist"),
      freedesktop   = require("compact.menu.freedesktop"),
      prompt        = require("compact.prompt"),
      weather       = require("compact.weather"),
      exit          = require("compact.exit"),
      
      net_dragonfly = require("compact.net_dragonfly"),
      net_fbsd = require("compact.net_fbsd"),
      places        = require("compact.places"),
      calendar      = require("compact.calendar"),
      orglendar     = require("compact.orglendar"),
      mixer         = require("compact.mixer"),
      treble        = require("compact.treble"),
      bass          = require("compact.bass"),
      memory        = require("compact.memory"),
      cpu           = require("compact.cpu"),     
     -- hammer2       = require("compact.hammer2"),
      clock         = require("compact.clock"),
      right         = require("compact.right"),
      middle        = require("compact.middle"),
      left          = require("compact.left"),
      zfs           = require("compact.zfs")
}    
