return {
      sox           = require("compact.sox"),
      playbar      = require("compact.sox.playbar"),  
      menu          = require("compact.menu"),
      layout        = require("compact.layout"),
      common        = require("compact.common"),

      unitybar      = require("compact.unitybar"),
      os              = require("compact.os"),
      titlebar      = require("compact.titlebar"),
      tasklist      = require("compact.tasklist"),
      freedesktop   = require("compact.menu.freedesktop"),
      prompt        = require("compact.prompt"),
      weather       = require("compact.weather"),
      exit            = require("compact.exit"),
      net             = require("compact.net"),
      places        = require("compact.places"),
      calendar      = require("compact.calendar"),
      orglendar     = require("compact.orglendar"),
      mixer         = require("compact.mixer"),
      treble        = require("compact.treble"),
      bass          = require("compact.bass"),
      memory        = require("compact.memory"),
      cpu           = require("compact.cpu"),     
     
      clock         = require("compact.clock"),
      right         = require("compact.right"),
      middle        = require("compact.middle"),
      left          = require("compact.left"),
      mount           = require("compact.mount")
}    
