return {
      menu          = require("compact.menu"),
      layout        = require("compact.layout"),
      common        = require("compact.common"),
      unitybar      = require("compact.unitybar"),
      tagmenu       = require("compact.tagmenu"),
      titlebar      = require("compact.titlebar"),
      tasklist      = require("compact.tasklist"),
      exit          = require("compact.exit"),
      prompt        = require("compact.prompt"),
      weather       = require("compact.weather"),
      skb_exit      = require("compact.skb_exit"),
      net           = require("compact.net"),
      places        = require("compact.places"),
      calendar      = require("compact.calendar"),
      orglendar     = require("compact.orglendar"),
      mixer         = require("compact.mixer"),
      treble        = require("compact.treble"),
      bass          = require("compact.bass"),
      memory        = require("compact.memory"),
      cpu           = require("compact.cpu"),
      zfs           = require("compact.zfs"),
      clock         = require("compact.clock"),
      right         = require("compact.right"),
      middle        = require("compact.middle"),
      left          = require("compact.left")
}    
